### ISSUE TITLE
CBSwinTransformer is not in the models registry

### ISSUE THREAD

**Issue by ahong007007** [VDIGPKU/CBNetV2#18]
When  Run the code demo/image_demo.py:

![image](https://user-images.githubusercontent.com/22077027/126942978-6e27b2c9-940e-4949-81a1-6c92dee30325.png)

configfile----"../configs/cbnet/htc_cbv2_swin_base_patch4_window7_mstrain_400-1400_giou_4conv1f_adamw_20e_coco.py"

checkpoint',"../htc_cbv2_swin_base22k_patch4_window7_mstrain_400-1400_giou_4conv1f_adamw_20e_coco.pth.zip",

**Comment by LLsmile** [comment]
I met the same question.
python tools/test.py configs/cbnet/htc_cbv2_swin_large_patch4_window7_mstrain_400-1400_giou_4conv1f_adamw_1x_coco.py checkpoints/htc_cbv2_swin_large22k_patch4_window7_mstrain_400-1400_giou_4conv1f_adamw_1x_coco.pth --eval bbox
loading annotations into memory...
Done (t=0.31s)
creating index...
index created!
Traceback (most recent call last):
  File "/home/liaolin/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/utils/registry.py", line 51, in build_from_cfg
    return obj_cls(**args)
  File "/home/liaolin/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmdet/models/detectors/htc.py", line 10, in __init__
    super(HybridTaskCascade, self).__init__(**kwargs)
  File "/home/liaolin/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmdet/models/detectors/cascade_rcnn.py", line 27, in __init__
    init_cfg=init_cfg)
  File "/home/liaolin/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmdet/models/detectors/two_stage.py", line 31, in __init__
    self.backbone = build_backbone(backbone)
  File "/home/liaolin/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmdet/models/builder.py", line 19, in build_backbone
    return BACKBONES.build(cfg)
  File "/home/liaolin/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/utils/registry.py", line 210, in build
    return self.build_func(*args, **kwargs, registry=self)
  File "/home/liaolin/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/cnn/builder.py", line 26, in build_model_from_cfg
    return build_from_cfg(cfg, registry, default_args)
  File "/home/liaolin/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/utils/registry.py", line 44, in build_from_cfg
    f'{obj_type} is not in the {registry.name} registry')
KeyError: 'CBSwinTransformer is not in the models registry'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "tools/test.py", line 237, in <module>
    main()
  File "tools/test.py", line 186, in main
    model = build_detector(cfg.model, test_cfg=cfg.get('test_cfg'))
  File "/home/liaolin/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmdet/models/builder.py", line 58, in build_detector
    cfg, default_args=dict(train_cfg=train_cfg, test_cfg=test_cfg))
  File "/home/liaolin/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/utils/registry.py", line 210, in build
    return self.build_func(*args, **kwargs, registry=self)
  File "/home/liaolin/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/cnn/builder.py", line 26, in build_model_from_cfg
    return build_from_cfg(cfg, registry, default_args)
  File "/home/liaolin/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/utils/registry.py", line 54, in build_from_cfg
    raise type(e)(f'{obj_cls.__name__}: {e}')
KeyError: "HybridTaskCascade: 'CBSwinTransformer is not in the models registry'"

**Comment by CharlesNJohn** [comment]
Were you able to fix it? I am facing the same issue now.

**Comment by CharlesNJohn** [comment]
> When Run the code demo/image_demo.py:
> 
> ![image](https://user-images.githubusercontent.com/22077027/126942978-6e27b2c9-940e-4949-81a1-6c92dee30325.png)
> 
> configfile----"../configs/cbnet/htc_cbv2_swin_base_patch4_window7_mstrain_400-1400_giou_4conv1f_adamw_20e_coco.py"
> 
> checkpoint',"../htc_cbv2_swin_base22k_patch4_window7_mstrain_400-1400_giou_4conv1f_adamw_20e_coco.pth.zip",

Were you able to fix this? @LLsmile  @ahong007007

**Comment by CharlesNJohn** [comment]
I was able to resolve it, it is caused because of improper installation of mmdet. Do not install it directly from the website. For SwinTransformers there is a directory in that repository, please install from that.

**Comment by tingtingliangvs** [comment]
Duplicate issue, please refer to #17
